scp -r ~/Dropbox/sites/seleccion/aspirantes/assets/* pi@intranet.local:~/seleccion/aspirantes/assets/
scp -r ~/Dropbox/sites/seleccion/aspirantes/config/* pi@intranet.local:~/seleccion/aspirantes/config/
scp -r ~/Dropbox/sites/seleccion/aspirantes/controllers/* pi@intranet.local:~/seleccion/aspirantes/controllers/
scp -r ~/Dropbox/sites/seleccion/aspirantes/models/* pi@intranet.local:~/seleccion/aspirantes/models/
scp -r ~/Dropbox/sites/seleccion/aspirantes/views/* pi@intranet.local:~/seleccion/aspirantes/views/
scp -r ~/Dropbox/sites/seleccion/aspirantes/web/css/* pi@intranet.local:~/seleccion/aspirantes/web/css/
scp -r ~/Dropbox/sites/seleccion/aspirantes/web/img/* pi@intranet.local:~/seleccion/aspirantes/web/img/
scp -r ~/Dropbox/sites/seleccion/aspirantes/web/js/* pi@intranet.local:~/seleccion/aspirantes/web/js/
scp -r ~/Dropbox/sites/seleccion/common/components/* pi@intranet.local:~/seleccion/common/components/
scp -r ~/Dropbox/sites/seleccion/common/config/* pi@intranet.local:~/seleccion/common/config/
scp -r ~/Dropbox/sites/seleccion/common/fixtures/* pi@intranet.local:~/seleccion/common/fixtures/
scp -r ~/Dropbox/sites/seleccion/common/helpers/* pi@intranet.local:~/seleccion/common/helpers/
scp -r ~/Dropbox/sites/seleccion/common/mail/* pi@intranet.local:~/seleccion/common/mail/
scp -r ~/Dropbox/sites/seleccion/common/models/* pi@intranet.local:~/seleccion/common/models/
scp -r ~/Dropbox/sites/seleccion/common/widgets/* pi@intranet.local:~/seleccion/common/widgets/
